In [2]:
import numpy as np
import pandas as pd

from sklearn.impute import MissingIndicator
 

In [4]:
features =[
    [4,2,1],
    [24,12,6],
    [8,4,2],
    [28,14,7],
    [32,16,-1],
    [600,300,150],
    [-1,60,30],
    [-1,4,1]
]

In [6]:
indicator = MissingIndicator(missing_values = -1)

In [11]:
bin_arr = indicator.fit_transform(features)
bin_arr

#the binary array only gives values for col that has missing value and true indicates missing values

array([[False, False],
       [False, False],
       [False, False],
       [False, False],
       [False,  True],
       [False, False],
       [ True, False],
       [ True, False]])

In [13]:
#features that have missing values

indicator.features_

array([0, 2])

In [16]:
# to show all features in binary matrix

indicator = MissingIndicator(missing_values = -1, features='all')
all_bin_arr = indicator.fit_transform(features)
all_bin_arr

array([[False, False, False],
       [False, False, False],
       [False, False, False],
       [False, False, False],
       [False, False,  True],
       [False, False, False],
       [ True, False, False],
       [ True, False, False]])