In [1]:
import numpy as np

In [2]:
arr1=[3,4,4,4,4,4]
print(type(arr1))

<class 'list'>


In [4]:
narr1=np.array(arr1)
print(type(narr1))

<class 'numpy.ndarray'>


In [5]:
narr2=np.array([[1,2,3,4],[2,3,4,5]])
print(type(narr2))
print(narr2)

<class 'numpy.ndarray'>
[[1 2 3 4]
 [2 3 4 5]]


In [6]:
print(narr1.shape)
print(narr2.shape)

(6,)
(2, 4)


In [7]:
zero_arr=np.zeros((3,3))
print(zero_arr)
one_arr=np.ones((2,3))
print(one_arr)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]]


In [8]:
full_arr=np.full((3,3),6)
print(full_arr)

[[6 6 6]
 [6 6 6]
 [6 6 6]]


In [9]:
eye_arr=np.eye(4)
print(eye_arr)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [10]:
narr3=np.array([0,9,8,7])
narr4= np.array([[1,2,3,4],[5,6,7,8]])
concat_arr1=np.concatenate([narr1, narr3])
concat_arr2=np.concatenate([narr2, narr4])
print(concat_arr1)
print(concat_arr2)

[3 4 4 4 4 4 0 9 8 7]
[[1 2 3 4]
 [2 3 4 5]
 [1 2 3 4]
 [5 6 7 8]]


In [11]:
#selection and indexing

print(narr2)
print(narr2[1][1])
print(narr2[1:3])
print(narr2[0:1])

narr5=np.array([2,3,4,5])
print(narr5)

narr5[2]=6
print(narr5)
print(concat_arr2[1,2])
print(narr2[0:1,0:3]) # row slice, column slice

bool_arr= narr2>3
print(bool_arr)
print(narr2[bool_arr])

narr2[narr2<3]


[[1 2 3 4]
 [2 3 4 5]]
3
[[2 3 4 5]]
[[1 2 3 4]]
[2 3 4 5]
[2 3 6 5]
4
[[1 2 3]]
[[False False False  True]
 [False False  True  True]]
[4 4 5]


array([1, 2, 2])

In [12]:
# vector arithmetics

x= np.array([1,2,3])
y= np.array([0,9,8])
print(y+2)
print(x+y)
print(x-y)
print(x*y)
print(y/x)

#dot product
print(np.dot(x,y))


[ 2 11 10]
[ 1 11 11]
[ 1 -7 -5]
[ 0 18 24]
[0.         4.5        2.66666667]
42


In [21]:
# matrix airthmetic

from numpy.linalg import inv

x= np.matrix([[1,2],[3,4]])
y= np.matrix([[3,4],[7,6]])
# matrix are strictly 2 dimensional
print(type(x))
print(x+y)
print(x-y)
print(x*y)
print(3*x)
print(np.multiply(x,y))#element-wise
print(x.T)
print(inv(x))

#dot product

x.dot(y)

<class 'numpy.matrix'>
[[ 4  6]
 [10 10]]
[[-2 -2]
 [-4 -2]]
[[17 16]
 [37 36]]
[[ 3  6]
 [ 9 12]]
[[ 3  8]
 [21 24]]
[[1 3]
 [2 4]]
[[-2.   1. ]
 [ 1.5 -0.5]]


matrix([[17, 16],
        [37, 36]])

In [14]:
#Broadcasting

q=np.arange(15).reshape(3,5)
print(q)

a=np.arange(5)
print(a)
print(q+a)
print(q-a)

z=np.arange(3).reshape(3,1)
print(z)
print(q+z)
print(q-z)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
[0 1 2 3 4]
[[ 0  2  4  6  8]
 [ 5  7  9 11 13]
 [10 12 14 16 18]]
[[ 0  0  0  0  0]
 [ 5  5  5  5  5]
 [10 10 10 10 10]]
[[0]
 [1]
 [2]]
[[ 0  1  2  3  4]
 [ 6  7  8  9 10]
 [12 13 14 15 16]]
[[ 0  1  2  3  4]
 [ 4  5  6  7  8]
 [ 8  9 10 11 12]]


In [15]:
#solve equations

x=np.array([[2,1],[1,-1]])
print(x)
b=np.array([4,-1])
print(b)
x_inv=np.linalg.inv(x)
print(x_inv)
y=x_inv.dot(b)
print(y)

x2=np.array([[1,2,3],[4,5,2],[2,8,5]])
b2=np.array([5,10,15])
np.linalg.solve(x2,b2)

[[ 2  1]
 [ 1 -1]]
[ 4 -1]
[[ 0.33333333  0.33333333]
 [ 0.33333333 -0.66666667]]
[1. 2.]


array([0.46511628, 1.39534884, 0.58139535])

In [22]:
#some basic statistic operations

narr6= np.array([[1,2,3,4],[4,5,6,7],[5,8,9,0],[6,2,4,6]])
print(narr6)
print(narr6.min()) # min val
print(narr6.max()) #max val
print(narr6.sum())#sum of all values
print(narr6.sum(axis=0))# column wise sum
print(narr6.sum(axis=1))# row wise sum
print(narr6.mean()) #mean
print(narr6.mean(axis=1))# row means
print(np.median(narr6)) #median
print(np.median(narr6, axis=0))# column-wise median
print(np.std(narr6)) #std
print(narr6.std(axis=0))# column standard deviation
print(np.percentile(narr6,50))
print(np.percentile(narr6,75, axis=0)) #75th percentile column wise

[[1 2 3 4]
 [4 5 6 7]
 [5 8 9 0]
 [6 2 4 6]]
0
9
72
[16 17 22 17]
[10 22 22 18]
4.5
[2.5 5.5 5.5 4.5]
4.5
[4.5 3.5 5.  5. ]
2.4238399287081647
[1.87082869 2.48746859 2.29128785 2.68095132]
4.5
[5.25 5.75 6.75 6.25]


In [17]:
np.linspace(5,20,10)

array([ 5.        ,  6.66666667,  8.33333333, 10.        , 11.66666667,
       13.33333333, 15.        , 16.66666667, 18.33333333, 20.        ])

In [18]:
#random

np.random.rand(5)
np.random.rand(3,4)

#gussian distribution

np.random.randn(2)
np.random.randn(3,1)
np.random.randint(1,100)
np.random.randint(1,100,11)

array([34, 75, 47, 36, 32, 25, 25, 71, 56, 81, 94])

In [19]:
#reshape

narr7=np.arange(25)
narr8=np.random.randint(0,60,11)

print(narr7,narr8)
narr7.reshape(5,5)


[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24] [42 51 14 55 26 19 36 30 42  3 10]


array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [20]:
#max and min

print(narr8.min())
print(narr8.max())

narr8.argmin()
narr8.argmax()


3
55


3